### ISSUE TITLE
install python support for RMQ

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#104]
installing python support for RMQ including pika, netCDF4, and json modules in user space

**Comment by jasonfleming** [comment]
I think this is working now, @wwlwpd can you confirm?

**Comment by wwlwpd** [comment]
> I think this is working now, @wwlwpd can you confirm?

Sorry, just saw this. I will get with @BrianOBlanton to confirm that all dependencies are getting installed.
