### ISSUE TITLE
FortCheck.py not able to load PyUnivodeUCS2_FromStringAndSize symbol

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#182]
When running on Frontera, the FortCheck.py script seems unable to load all required symbols ... the error message is as follows:

Traceback (most recent call last):
  File "/work/00976/jgflemin/frontera/asgs/jasonfleming/asgs/monitoring/FortCheck.py", line 2, in <module>
    from netCDF4 import Dataset
  File "/home1/00976/jgflemin/.local/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: /home1/00976/jgflemin/.local/lib/python2.7/site-packages/netCDF4/_netCDF4.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize

**Comment by jasonfleming** [comment]
Is this relevant?

https://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8

**Comment by wwlwpd** [comment]
> Is this relevant?
> 
> https://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8

I will see if it is.

@jasonfleming, does the 'verify' command in asgsh shell expose this or only when the script is actually being used?

**Comment by jasonfleming** [comment]
The output from verify shows all ok. The path to the python interpreter seems to be correct:

asgs (tx2008_r35h_nam)> which python 
/work/00976/jgflemin/frontera/opt/python/2.7.17/bin/python

**Comment by wwlwpd** [comment]
@jasonfleming would you mind listing out some steps to reproduce?

**Comment by wwlwpd** [comment]
I suspect that we are not installing scipy. Can you run the following command while in asgsh and let me know if you get the same issue:

    pip install --user scipy -I

**Comment by wwlwpd** [comment]
Oh I think this is the issue, https://github.com/Unidata/netcdf4-python/issues/512

**Comment by wwlwpd** [comment]
the plot thickens, https://stackoverflow.com/questions/31471751/how-can-i-install-netcdf4-python-to-ubuntu14-04#31734420

**Comment by wwlwpd** [comment]
More that are helpful
https://stackoverflow.com/questions/18107298/cannot-install-netcdf4-python-package-on-os-x
https://code.google.com/archive/p/netcdf4-python/wikis/UbuntuInstall.wiki

I think it's related to setting the right flags to the HDF5 and NetCDF compiled library

**Comment by wwlwpd** [comment]
@jasonfleming was your solution here just to load the python module on frontera?

**Comment by jasonfleming** [comment]
Hey @wwlwpd the init_frontera() function in platforms.sh still had RabbitMQ using the tacc python module ... my fix was to switch it to the python installed by asgs brew instead.

**Comment by wwlwpd** [comment]
Great! Well the latest PR adds some missing things we needed anyway, plus 2 more verification scripts - one is a benchmark.
