### ISSUE TITLE
allow asgs-brew.pl to work if the install directory contains shell variable

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#200]
I tried to use init-asgs.sh on stampede2 and specify the install directory as $WORK/opt ... however the compilation of HDF5 stopped with an error that it could not find ORK/opt ... there may be an issue of shell expansion somewhere in the process.

**Comment by wwlwpd** [comment]
Did you enter it literally as `$WORK/opt` into the dialog? I suspect that variable expansion is not happening in in the `read` input entry. In the following example, it assigns the literal string with the string `$FOO`

    read -p "what's your home dir [$HOME]? " home && echo $home
    what's your home dir [/home/user]? $FOO
    $FOO

I'll do some more digging on the `read` function, but what do you think about checking to see if `$WORK` is set and default to that as the base directory if so?

**Comment by jasonfleming** [comment]
Hey @wwlwpd I was thinking we could just caution the Operator not to use shell variables. :-) The default location would have to be different on different platforms, I would think. It may also vary according to the Operator. For TACC systems, $WORK would be a great default. Some Operators there might choose $HOME instead. For hatteras, there is no $WORK, and I don't think Brian uses $HOME either, so that platform is more ambiguous.

**Comment by wwlwpd** [comment]
addressed with a comment and defaulting path to one based on `$WORK`.
