### ISSUE TITLE
init-asgs.sh provides unexpected profile name in suggested asgs-brew.pl cmd line

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#227]
[ncfs@ht4 15:55:04 asgs]$ ./init-asgs.sh
pod            - POD (Penguin)
hatteras       - Hatteras (RENCI)
supermike      - Supermike (LSU)
queenbee       - Queenbee (LONI)
supermic       - SuperMIC (LSU HPC)
lonestar5      - Lonestar (TACC)
stampede2      - Stampede2 (TACC)
frontera       - Frontera (TACC)
desktop        - desktop
desktop-serial - desktop-serial
poseidon       - Poseidon
penguin        - Penguin
rostam         - rostam
vagrant        - vagrant/virtual box (local workstation)

Which platform environment would you like to use for ASGS bootstrapping? hatteras

Which asgs branch would you like to checkout from Github ('.' to skip)? [master] 
Already on 'master'
Your branch is up-to-date with 'origin/master'.

Which compiler family would you like to use, 'gfortran' or 'intel'? intel

Where do you want to install libraries and some utilities? [/home/ncfs/opt] 
(note: shell variables like $HOME or $WORK will not be expanded)? 

What is a short name you'd like to use to name the asgsh profile associated with this installation? ["default"] 
Bootstrapping ASGS for installation...
platforms.sh>env_dispatch(): Initializing settings for hatteras.

./cloud/general/asgs-brew.pl --install-path=/home/ncfs/opt --asgs-profile=14097 --compiler=intel --machinename=hatteras --make-jobs=8

Run command above, y/N? [N]

**Comment by wwlwpd** [comment]
Thank you! I ran into this today when going over things with @mattbilskie.

**Comment by wwlwpd** [comment]
Oh, and will have a fix this evening.

**Comment by wwlwpd** [comment]
Fixed in latest run-ready-2020 branch
