### ISSUE TITLE
high memory usage by NAM2OWI.pl

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#31]
As reported by @BrianOBlanton : The NAM2OWI perl code reads a bunch of text data into memory for later output, and this can cause the processing job to die w/o diagnostics when running on a vm with 2Gb of memory.  This processing job can be moved to a compute node, but eventually we should re-write this perl code to be more efficient...

**Comment by estrabd** [comment]
Lines 145 and 250 of https://github.com/jasonfleming/asgs/blob/master/NAMtoOWI.pl

Slurping the contents of a file using the syntax,

    my @array = <myFH>;

Is going to cause the memory issue.

Better is the following, which I saw in a few other places in that file:

    open my $fh, q{<}, q{/path/to/file};
    foreach my $line (<$fh>) {
      #... process line
    }
   close $fh;

**Comment by jasonfleming** [comment]
Resolved by #79.
