### ISSUE TITLE
add queenbee3 support

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#327]
http://www.hpc.lsu.edu/docs/guides.php?system=QB3

**Comment by jasonfleming** [comment]
Ok I will add this to the resource management spreadsheet (mostly blanks for now, but it gets the ball rolling).

**Comment by wwlwpd** [comment]
started hammering this out in https://github.com/jasonfleming/asgs/commits/issue-327 - @jasonfleming @mattbilskie @akheir (no rush atm)

**Comment by wwlwpd** [comment]
I am doing it the traditional way so that when I address do some more aggressive platform clean up I'll capture all of them at the same time, note QB3's docs - http://www.hpc.lsu.edu/docs/guides.php?system=QB3 (as @jasonfleming mentioned, it uses slurm)
