### ISSUE TITLE
enable automated building of adcirc v54 and adcirc v55 in asgs brew

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#391]
This is a prerequisite for running with the latest version(s) of adcirc in the 2021 season. This enhancement should wait until we have tagged the 2020stable version of asgs.

**Comment by wwlwpd** [comment]
This is great. We're going to have to figure out what to do about `cmake` and establish a more formal workflow with upstream ADCIRC development. As part of this I'd prefer to tie in supporting the makefile infrastructure, at least for ASGS needs. Quick look across platforms shows that cmake is available via `modules` but that's a risky proposition as we've seen before. Frankly, I'd rather commit to maintaining the makefile infrastructure. Anyway, discussion is needed on that part.

**Comment by wwlwpd** [comment]
Current tact is to go with v55 only, testing on queenbee in v55 the
make command to "make unhcat" fails:

  make: *** No rule to make target `unhcat'.  Stop.

Will update comments with more information as we proceed on QB.

**Comment by wwlwpd** [comment]
Another error,

```
ifort -c -O2 -W0 -assume byterecl -traceback -diag-disable 8290 -diag-disable 8291 -diag-disable 8293  -I /work/asgs/adcirc-cg-v55release-intel/work/odir33/ -
o /work/asgs/adcirc-cg-v55release-intel/work/odir33/swanpre2.o  /work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f
Cannot disable Fortran error message 7002
/work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f(1031): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [SWN_O
UTNC]
      USE swn_outnc                                                       41.52
----------^
compilation aborted for /work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f (code 1)
make[1]: *** [/work/asgs/adcirc-cg-v55release-intel/work/odir33/swanpre2.o] Error 1
make[1]: Leaving directory `/work/asgs/adcirc-cg-v55release-intel/work'
make: *** [adcswan] Error 2
```

**Comment by jasonfleming** [comment]
Thank you Brett, that is interesting, I will give it a shot too so I can reproduce it. Let's keep a record of the platforms where we see this and those that we don't (if any).

**Comment by wwlwpd** [comment]
Skipping v54, going straight for v55. Seems the only breakages
that I can find are related to the building of `adcswan` and `padswan`.

`adcirc` and friends build fine as far as I can tell via `work/makefile`,
so the only conclusion I can currently see is that the breakage of the
SWAN binaries in v55release is related to the moving of the `./swan`
directory to `./thirdparty/swan`. Will do some more investigation. Current
error is (on supermic, but the same on QB):

> ifort -c -O2 -W0 -assume byterecl -traceback -diag-disable 8290 -diag-disable 8291 -diag-disable 8293  -I /worka/work/asgs/adcirc-cg-v55release-intel/work/odir33/ -o /worka/work/asgs/adcirc-cg-v55release-intel/work/odir33/swanpre2.o  /worka/work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f
> Cannot disable Fortran error message 7002
> /worka/work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f(1031): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [SWN_OUTNC]
>       USE swn_outnc                                                       41.52
> ----------^
> compilation aborted for /worka/work/asgs/adcirc-cg-v55release-intel/thirdparty/swan/swanpre2.f (code 1)
> make[1]: *** [/worka/work/asgs/adcirc-cg-v55release-intel/work/odir33/swanpre2.o] Error 1
> make[1]: Leaving directory `/worka/work/asgs/adcirc-cg-v55release-intel/work'
> make: *** [adcswan] Error 2
