### ISSUE TITLE
clarify support committment to file systems with case insensitive file names and other restrictions

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#408]
@jasonfleming - let's clarify if we're supporting "case insensitive" file systems (e.g., ce4b72df657b0943e1ba4e70da4af41fa16851c2).

This will only be the case on 2 platforms: Windows and Mac OS (depending on the FS settings used). I can see this being an issues if one wished to "checkout" the repo on either kind of machine - certainly, we don't support running ASGS on either (hence the docker approach). I just want to make sure this isn't considered a priority kind of thing since both environments might make the new names of the "offending" files become awkward. No big deal, I've run into this before. But I did want to have a brief chat about it so we can clarify when we'd need to do this and how aware we need to be in the future when considering file names, etc.

**Comment by jasonfleming** [comment]
Thank you Brett ... I agree that we need to clarify and for my part I don't think we need to support case insensitive platforms. :-) However I would like to be able to clone the repo on my Windows laptop successfully. The only reason why this failed in this case was that there were two files with exactly the same name (only differing according to capitalization). What about a policy that just makes sure that the spelling of different files differs by more than the capitalization? It seems like this would reduce confusion in any case.

**Comment by jasonfleming** [comment]
I have now added a comment on this to the ASGS Wiki that clarifies that files in the same directory should have names that differ by more than the capitalization.
