### ISSUE TITLE
create Alpine-based Dockerfile for ADCIRPOLATE and deploy with Singularity

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#433]
The [ADCIRPOLATE](https://github.com/ccht-ncsu/Adcirpolate) (or "switch-on-the-fly") project enables us to hotstart one mesh from another by interpolating the underlying solutions, which will greatly improve our operational flexibility. This workflow runs in parallel and has several dependencies, notably ESMF and netCDF. Containerizing this workflow and developing the capacity and documented processes to deploy the associated image from Dockerhub across our suite of HPC platforms with Singluarity will facilitate the operational agility provided by this workflow.

**Comment by wwlwpd** [comment]
Progress is being made; started with this Dockerfile - https://github.com/BryanDollery/esmf-docker/blob/master/Dockerfile but it's proving to be quite broken; still gives a good idea on what needs to be done for esmf
