### ISSUE TITLE
add flex to docker containers to support building of nco

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#444]

**Comment by wwlwpd** [comment]
Is this required for you on ubuntu for NCO?

If it is, I recommend we add it as a package installation in the Ubuntu
and Debian (and future Alpine) Dockerfiles. (e.g., `apt-get install -y flex`).

If you're seeing this on an HPC platform, the I agree it probably should be
supported in `asgs-brew.pl`.

**Comment by wwlwpd** [comment]
Disregard. Done.
