### ISSUE TITLE
make qscript.pl add -R to command line options to padcirc and padcswan when asgs HOTSTARTCOMP=subdomain

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#447]

**Comment by wwlwpd** [comment]
thanks for assigning this to yourself, lets me know you intend to work on it; don't hesitate to assign me to stuff - this is actually helpful for me know know expectations :)

**Comment by wwlwpd** [comment]
I recommend we get this merged before #450 is started, or conversely include #450 as part of this work, just as a separate commit.
