### ISSUE TITLE
integrate small patch into adcirc build, needed by adcirpolate 

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#454]
The adcirpolate capability requires that the target mesh be run with a (lightly) patched version of adcirc that does some extra calculations upon hotstarting when computing wet and dry locations. I believe the changes are limited to about a dozen lines in hstart.F in the adcirc source code. I think we'd need to maintain a patch for v53 and, more importantly, v55. This patch should be propagated upstream in the case of v55 so we can eventually drop it for adcirc versions after that.

**Comment by jasonfleming** [comment]
To see the changes, search for "cnd" in https://github.com/adcirc/adcirc-cg/blob/Clint-Interpolation/Interpolation-v2/v53version_test/src/hstart.F

Here is the relevant snippet in `hstart.F`:
```
cnd   changes for when using interpolation
         do i=1,np
            if ((dp(i).le.0.).and.(dp(i)+ifnlfa*eta2(i).lt.H0)) then
!  this is the case if the node is dry in the new mesh 
               eta2(i)=H0-dp(i)
               eta1(i)=eta2(i)
               uu2(i)=0.0
               uu1(i)=0.0
               vv2(i)=0.0
               vv1(i)=0.0
               nnodecode(i)=0
            endif
!   next is the case if we're on land but the region has already flooded  
            if ((dp(i).le.0).and.(dp(i)+ifnlfa*eta2(i).ge.H0)) then
               nnodecode(i)=1
            endif
!   the node is wet
            if (dp(i).gt.0) nnodecode(i)=1
!            if ((abs(eta2(i)).gt.10).and.(dp(i).gt.0.0)) then
!               write(1002,*) 'on myproc ',myproc
!               write(1002,*) "Elevation at node ", i, "is ", eta2(i),dp(i)
!               write(1002,*) "Velocity is x: ", uu2(i), "y: ", vv2(i)
!               write(1002,*) "Node code  : ", nnodecode(i)
!            endif 
c  this is a temporary fix only due to interpolation problems!!!
c            if (slam(i)/deg2rad.gt.-78.) then
c               eta2(i)=0.0
c               uu2(i)=0.0
c               vv2(i)=0.0
c               if (dp(i).gt.0.) nnodecode(i)=1
c            endif
!         enddo
         call computeWettingAndDrying(ITHS)
cnd
```
We will have to work together to integrate this, since the current placement of these calculations means that they will only get executed after the reading of the binary hotstart file; we need to make sure they are also executed if a netcdf hotstart file is read in.

**Comment by wwlwpd** [comment]
I will add the patches. I need to think about "patch" management. Each mutually exclusive patch set we maintain effectively constitutes a new version supported. We should also be handing the `qbc` makefile additions as a patch.

**Comment by wwlwpd** [comment]
Also have questions about _what_ to "diff".

**Comment by wwlwpd** [comment]
@jasonfleming, I have a diff created against `v53release`
of ADCIRC. I am not sure if it's linked to this case yet,
but it's in my remote and you can checkout the branch:

```
git remote add wwlwpd git@github.com:wwwpwd-dev/_asgs.git
git fetch --all
git checkout issue-454
```

If this is an acceptible format for you to determine this;
can you suggest a better place in `src/hstart.F` to place this,
or would you just want it to be separated out as a function?

Once this is done, it'd be probably straightforward for you
to help me determine in ADCIRC `v55.00`'s `src/hstart.F` where
this should go.
