### ISSUE TITLE
automate installation of asgs on hpc platforms where default configuration is already established

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#64]
The step-by-step installation process of the ASGS described in the ASGS Developers is actually relatively simple and could easily be automated. In addition, the acquisition of a mesh from a remote mesh server could also be automated. The master branch of the ASGS has code for downloading and compiling ADCIRC with a operator-configurable set of compiler flags (e.g., to turn netcdf on or off, to compile with or without debugging, etc). Although the process of extending the asgs to a new hpc platform where it has never run will always require manual processes, the installation process could be completely scripted.

**Comment by jasonfleming** [comment]
@wwlwpd This milestone includes the following: 

- [ ]  autodetecting operator and platform so we don't need the -e command line option for execution and we don't need Operator- or platform-specific settings in the individual asgs config files
- [ ]  Operator can specify just the mesh to be used (i.e., GRIDNAME) in the asgs config file, and asgs knows where to find that mesh and associated nodal attributes and offset files in INPUTDIR, and if they are not found there, asgs can go to our digitalocean cloud space and try to download the associated files, e.g.,
>  https://asgs-static-assets.sfo2.digitaloceanspaces.com/meshes/hsofs.14.xz
> https://asgs-static-assets.sfo2.digitaloceanspaces.com/nodal-attributes/hsofs.13.xz
> https://asgs-static-assets.sfo2.digitaloceanspaces.com/offsets/unit_offset_hsofs.dat.xz

This may require a "mesh inventory" meshes.sh file similar to platforms.sh that contains default parameters for each mesh, including the urls for associated file, the TIMESTEPSIZE parameter, appropriate ptFile to use, station file names, control template file to use, template file properties, etc. I can help with this. 
- [ ] Default locations for PREPPEDARCHIVE and HINDCASTARCHIVE tar.gz files should be in SCRATCH instead of INPUTDIR
- [ ] netcdf4/hdf5 build and install
- [ ] perlbrew build and install
- [ ] installing python support for RMQ including pika, netCDF4, and json modules in user space
- [ ] build and install gdal, gmt, shorelines data file, and imagemagick (if necessary); all to support FigureGen
- [ ] continue to support existing automated installation of wgrib2, tide_fac.f, etc but add clean up of intermediate .mod .o and grib2/* files 
- [ ] build all fortran utilities in subdirectories wherever the makefiles already exist
- [ ] make it work on all platforms including: lonestar5, stampede2, queenbee, supermic, supermike2, hatteras, penguin, and vagrant for vm (ubuntu 18.04LTS or similar)
- Does NOT include automated download/build of ADCIRC.
- Should be implemented in a branch from current master.

**Comment by wwlwpd** [comment]
Sounds good, will come up with some questions for our call tomorrow.

**Comment by jasonfleming** [comment]
I made a little prototype of the meshes.sh file and committed it to the master branch. It is not complete but gives a basic idea.

**Comment by wwlwpd** [comment]
I moved the mile stone description to a GH milestone, https://github.com/jasonfleming/asgs/milestone/18

**Comment by jasonfleming** [comment]
This was migrated to a GH milestone and has been completed.
