### ISSUE TITLE
numerical instability detection

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#7]
ASGS can't tell when ADCIRC or ADCIRC+SWAN is having numerical instabilities.

**Comment by zcobell** [comment]
Jason –

Could a simple, maybe temporary, fix for this be for ADCIRC to be compiled with -DWARN_ELEV_DEBUG. Then, ASGS could easily detect the fort.69 file presence.

Maybe it is worth removing the WARN_ELEV_DEBUG flag from ADCIRC and having ADCIRC detect the fort.15 parameters that control it to enable this option. Then, ASGS could always enable this function during fort.15 creation to detect instabilities.

Zach

--
Zach Cobell
Mobile: (908)489-0558
zachary.cobell@arcadis.com<mailto:zachary.cobell@arcadis.com>

**Comment by jasonfleming** [comment]
I think the short term solution here is for ASGS to look at the adcirc.log file (assuming nscreen was negative, come to think of it maybe ASGS should require nscreen to be negative) or stdout and see if it finds the strings WarnElev or ErrorElev, assuming the code exited without any other error. 

I do agree that we should remove the WARN_ELEV_DEBUG flag from ADCIRC (without breaking backward compatibility for fort.15 files that do not have the required parameters) but that would be an ADCIRC enhancement.

**Comment by natedill** [comment]
I use the following command as a quick check for stability warnings.  Maybe putting this in asgs_main.sh at the appropriate spots could do it. 

grep -i warnelev PE*/fort.16 | wc -l

if it returns a zero there are no warnings. 
Without the | -wc l  it tells you which subdomain(s) are having problems

**Comment by jasonfleming** [comment]
Hey @natedill on hatteras at least I am doing this via the following code at the end of the queue script:

```
ERROVALUE=$?  # capture exit status
if [ $ERROVALUE == 0 ] ; then
   # look for numerical instability errors in the stdout/stderr files
   for file in adcirc.log %advisdir%/%enstorm%/%jobtype%.%enstorm%.out ; do
      if [ -e $file ]; then
         numMsg=`grep WarnElev $file | wc -l`
         if [ $numMsg = 0 ]; then
            DATETIME=`date +'%Y-%h-%d-T%H:%M:%S'`
            echo "[${DATETIME}] INFO: %jobtype%.slurm: No numerical instability detected in $file after executing %jobtype%.%enstorm%." | tee --append %syslog%
         else
            ERROMSG="$ERROMSG Detected $numMsg numerical instability messages in $file."
            ERROVALUE=1
         fi
      fi
   done
else
   ERROMSG="The %jobtype%.%enstorm% job ended with an exit status that indicates an error occurred."
fi
```
I'm not sure if I've propagated this error detection to all our queue scripts for all our platforms yet though. Once I've confirmed this, I'll be able to close this out.

**Comment by jasonfleming** [comment]
I have now implemented this on both SLURM and PBS at the end of the queue script templates.
