### ISSUE TITLE
perl tidy

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#80]
Perl style varies from file to file, let's use perl tidy on all perl scripts in the repo and commit the result so we have a consistent style.

**Comment by wwlwpd** [comment]
As part of this work, I will also commit a standard ".perltidyrc" file that users can drop into their $HOME directory or include explicitly

**Comment by wwlwpd** [comment]
Also address in CONTRIBUTING information - please reopen if need arises again. `Perl::Tidy` is also installed with the `asgs-brew.pl` based environments.
