### ISSUE TITLE
get all Perl scripts ready to work in perlbrew environment

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#83]
Mainly this will entail making sure that all shebang lines are "#!/usr/bin/env perl" and that the the perlbrew environment is available (if needed) during batch jobs.

**Comment by jasonfleming** [comment]
Hey Brett I think this is resolved now, is that correct?

**Comment by wwlwpd** [comment]
>this is resolved now, is that correct?
Yes, thanks!
