### ISSUE TITLE
disable ssh StrictHostKeyChecking to avoid ssh hangs on new hosts

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#89]
When attempting to automatically scp results to a remote host, the ssh client will interactively notify the Operator that the remote host has not been contacted before (or that the remote host's key has changed) and ask if the connection should be made. This is an issue because it is a manual step that the Operator may not know about and the interactive notification maybe inside a screen session with no indication about why the session seems to have hanged. This issue can be resolved by adding a step to the asgs install procedure that adds the line "StrictHostKeyChecking no" to the Operator's "~/.ssh/ssh_config".

**Comment by wwlwpd** [comment]
Hi Jason, what's the action item for this. Happy to do it, but not sure where to apply said recommendation.

**Comment by jasonfleming** [comment]
I have resolved this with command line options to scp and ssh in output/opendap_post.sh.
