### ISSUE TITLE
Add basin identifier to opendap path for tropical cyclone instances

### ISSUE THREAD

**Issue by natedill** [jasonfleming/asgs#92]
That way the convention can be used if we ever do forecasts for other basins.  It also makes it more clear which is the storm number and which is the advisory number in the path e.g. http://tds.renci.org:8080/thredds/catalog/2018/al07/04/LA_v17a-WithUpperAtch_chk/queenbee.loni.org/072018LAv17a/nhcConsensus/catalog.xml  (note the "al07")

A quick modification would just add "al" to the opendap path assuming it is always the North Atlantic basin.  

A more comprehensive solution would have the ASGS keep track of the basin identifier from the ATCF and could use the information for other purposes (e.g. reverse the wind direction for storms in the southern hemisphere)

**Comment by jasonfleming** [comment]
Hey @natedill I have now made the change to hardcode the "al" into the opendap path. The fixed version is available on both the 2014stable and master branch. I will create a separate issue to track the autodetection of the basin and its placement in the opendap path, which is the preferred behavior in the long term.
