### ISSUE TITLE
Add tool for AWS SES (simple email service) integration

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#95]

**Comment by wwlwpd** [comment]
Required modules:

Email::Sender::Simple
Email::Sender::Transport::SMTP::TLS
Email::Simple::Creator
Config::Tiny
Try::Tiny

Brain dump from setting up domain with AWS - note all of this takes some time due to DNS propagation requirements.

1. get domain
2. get AWS account (note SES is in sandbox initially, and it requires a support ticket to boost it into production, until then sending limits and "to" restrictions are severely limited)
3. on registrar create an email forward record, verify
4. on AWS verify email address (takes time for DNS to propagate)
5. on AWS verify domain (adding SPF, DKIM records on registrar side - DNS so takes time)
6. configure "mail from" on AWS https://docs.aws.amazon.com/ses/latest/DeveloperGuide/mail-from-set.html
7. create SMTP credentials
8. test asgs-sendmail.pl with credentials

**Comment by jasonfleming** [comment]
Hey Brett it looks like this is complete, should we close this now?

**Comment by wwlwpd** [comment]
>should we close this now?
Yes, thanks!
