### ISSUE TITLE
synchronize multiple runs on different meshes to get posted for the same cycle

### ISSUE THREAD

**Issue by carolakaiser** [jasonfleming/asgs#98]
The CERA website shows the latest ASGS run by default. If runs for several meshes get posted, it would be a desired behavior if those runs all had the same run start time.

Possible fix: change get_nam.pl (e.g., asgs finishes a forecast from the day before and then the current cycle is 12Z today, asgs should go back to the 06Z and do that forecast instead of the latest).

**Comment by jasonfleming** [comment]
This is a duplicate with issue #151 ... I have just made a branch and committed a change that will allow the Operator to specify "strict" adherence to the selected forecast cycles.
